### ISSUE TITLE
Check if WHERE part of SELECT statement is optional.

### ISSUE THREAD

**Issue by pstutz** [uzh/triplerush#10]

**Comment by kjetilk** [comment]
It isn't: http://www.w3.org/TR/sparql11-query/#rSelectQuery but the "WHERE" keyword itself is optional. :-)

**Comment by pstutz** [comment]
Hey Kjetil, thanks for the information. How are you?

TR thinks WHERE is mandatory, so I should fix this bug. Btw: S/C and TR are finally Maven Central. One dependency is still from a custom repo, but once that one is also on MC I'll update the getting started description.

**Comment by kjetilk** [comment]
You're welcome! I'm fine, if a little stressed out with the ESWC deadline. :-) Great to hear it is released!
