### ISSUE TITLE
Ensure cardinalities are updated in `Binding` before a blocking edge addition finishes

### ISSUE THREAD

**Issue by pstutz** [uzh/triplerush#27]

**Comment by jahangirmohammed** [comment]
@pstutz : why is it that `SOIndex` doesn't do anything on `onEdgeAdded` method ?

**Comment by pstutz** [comment]
Because it doesn't have a parent index vertex that needs to have its cardinalities updated. Those cardinalities were used for query planning, maybe we should remove them, as they aren't used at the moment. But then again, we will probably want to re-introduce a query planner and then they'll be helpful.

**Comment by pstutz** [comment]
Fixed by no longer maintaining cardinalities.
